######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 24 09:36:40 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += chat.h login.h privchat.h
FORMS += chat.ui login.ui privchat.ui
SOURCES += chat.cpp login.cpp main.cpp privchat.cpp
