all:
	gcc complex_demo2.c

all2:
	gcc simple_state_machine.c

t:
	./a.out 123ab34.ac24.4.+-3ab+34.3

t1:
	gcc main.c -o demo1

t2:
	gcc main2.c -o demo2

r1:
	./demo1 < input.dat

r2:
	./demo2 < input.dat
