string:
	gcc -o test_string string_family.c

getput:
	gcc -o test_get_put get_put.c

printf:
	gcc -o test_printf printf_family.c 

all: 
	gcc -c -o hello.o hello.c
	gcc -o hello hello.o


t:
	./hello
