######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 19 22:40:31 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += clientsocket.h serversocket.h
SOURCES += clientsocket.cpp main.cpp serversocket.cpp
